services:
  risk-calculator-api:
    image: risk-calculator-api:latest
    container_name: risk-calculator-backend
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # OpenTelemetry configuration for local development (optional)
      # Uncomment below lines to test OTLP export locally
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      # For Grafana Cloud (production), use these instead:
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-east-2.grafana.net/otlp
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic Z2xjX2V5SnZJam9pTVRVeE5qVTRNaUlzSW01SWFXNTZJAUI
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/RiskCalculator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - risk-calculator-network

networks:
  risk-calculator-network:
    driver: bridge
