server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs from risk-calculator
  - job_name: risk-calculator-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: risk-calculator-api
          environment: development
          service: risk-calculator
          __path__: /var/log/app/*.log

  # Docker container logs
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            logger: logger
      - labels:
          level:
          logger:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
